server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/new?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=cy123456

# new
# ????
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# MyBatis
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

file.upload-path=D:/uploads/goods

alipay.app-id=9021000149673715
alipay.merchant-private-key=MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC6KgGTLmMGtLFDaHY4j0Jft0XkdTJ8/2euB2ly9MSQPHDC8TbVnxESDnTtgYC+pkP/T0RvzfDy5P7WRachYF9oKitq/kyEZCJVBIoE1D8GKYBUhdDXLQ2yudwLLOysmORuA61PnSY4UgVYtHoMJ4R85iAtCICEno5F0p0OuRoDva4rsMj8MQmKZmYleompBAmveILPPKPderziPTD5pwYO0+IgvVdTEAvCeVm2K9NMNHEseL8effV+jt+JD+yP/ZioOkDmkw33dGicbxFCwLVgbvhxoDYXFzB6lbMdS+ZqZXqFAxksFX+jii9pqCqp8ql/YVV8k6p+kJgYc7cxJt2DAgMBAAECggEBAJa7vFq3jGa5l23E/zP8ivmFI4o/eonLIt++EJuLpDxFM+gj9wowqVm9at+DpAK6DQSD4h3E2ftRfyVvcEuOBLIKsu0Gyl3H1iSQcFBIql8K62WEk/wl9pln88r4rQlzIkIRqBp2W6PuhXW1a7y7ooKesh7Ea4r19qyCQ7jQF0g+wsedt1DJB6uklH7CRrLDXOwy380Jjf2p7pb3xFXl6to3QKfMCrS50jRTf/SzT+k+KW23J4S/jjkbWhvrxzJmN4eUcZILb+dMduP2030nifKPuK5c70l6kICuFDhp421t6ZWcemMIehTTRN3TW55liVBcWT+ryHi3UUfe+3gurIECgYEA58Pe6/5BGaT92c9bmxJKX0v5mCzLta6l0NvJQIaNN1BS5FaoRRp6tZ2t5VOz47cXRujNrJqZDDrm96QXaQDVuAndtZaDs3LNqQL99JiZ7gaSvz4QbSMJ3JU7xhIwD/OFtSnhuujixn83UitRt8gCXpSzB8LD5Euv0xRwvBlbLekCgYEAzaFwiDTHaQXigeZRO8EXry0xl3aDet15WrYHbtvzybnmovEKXkmymLqXt4AOFh3nT/PtqXDo8waNc+uUp2JSKwpK0tYdUMdwJTe7Bhski2cq3T0u7FBctTdzEPGlLbEvPho5GqWGLeeMq9Y1ImdbDCvq481Q/UCAxkEu7J+3cIsCgYEAhWg9/WHRX02VwbaWaGDS5p/5ABto9x+c2uhoo/fPebOGw2EOYxim4bvtyT+xILbXcz22hlBHIL8XDB0sTIjqfJFRSaFmFflTYKIURKNCl7y449R56BhvKMXOLmlxuPzYTjvZb5l2UAQSd/3vf/ZlRsQZebImyFa40qvFaMC/t2ECgYA1XvuIPrqrJZ3evVrEOZ/eFcrTVy1VDHrc8nYHbgtehmO4Uvuv8UzrmzKZrCD72JMbC2LaIbY0rbS1K6YPs9ND3I4DHxPIzZrr7gUa1pyrmgFkHuc46rrFRjkVYsLOkziB0+iSY/fpnjnCt/xei5j0FcoHiljFAqLp0i1NuT6xdQKBgBizgNZaTsenHIFAZ3rgEk1Vfk93LUOEbpiv2qvS7MyGJJCKp/8S0ZCD9BXAWbbeGu+fm0Jj8cIRLk/beLgYWVWQWhP6NCjCxItM/U1Wb38ziaQ3P79F4xCJ1d0yagsFOlUXH+o85wed8zjYcAftfy7mq+ftRpPtP90pH5QgLXVe
alipay.alipay-public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuioBky5jBrSxQ2h2OI9CX7dF5HUyfP9nrgdpcvTEkDxwwvE21Z8REg507YGAvqZD/09Eb83w8uT+1kWnIWBfaCorav5MhGQiVQSKBNQ/BimAVIXQ1y0NsrncCyzsrJjkbgOtT50mOFIFWLR6DCeEfOYgLQiAhJ6ORdKdDrkaA72uK7DI/DEJimZmJXqJqQQJr3iCzzyj3Xq84j0w+acGDtPiIL1XUxALwnlZtivTTDRxLHi/Hn31fo7fiQ/sj/2YqDpA5pMN93RonG8RQsC1YG74caA2FxcwepWzHUvmamV6hQMZLBV/o4ovaagqqfKpf2FVfJOqfpCYGHO3MSbdgwIDAQAB
alipay.notify-url=http://localhost:8080/api/pay/notify
alipay.return-url=http://localhost:8080/payResult.html
alipay.gateway-url=https://openapi-sandbox.dl.alipaydev.com/gateway.do